name: Automated staging deployment
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: psf/black@stable
        with:
          version: 22.3.0
  build-push-frontend:
    needs:
      - lint
    uses: ./.github/workflows/docker-build.yaml
    with:
      dockerfile: ./docker/frontend.dockerfile
      imageName: mystic-chat-frontend
      imageTag: staging
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
      FULL_BUILD: "true"

  build-push-backend:
    needs:
      - lint
    uses: ./.github/workflows/docker-build.yaml
    with:
      dockerfile: ./docker/backend.dockerfile
      imageName: mystic-chat-backend
      imageTag: staging
    secrets:
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
